### ISSUE TITLE
Not Working with Windows Forms Applications

### ISSUE THREAD

**Issue by rcaroncd** [med0x2e/GadgetToJScript#7] opened 2021-06-09 17:14 UTC
Hello,

I was trying to convert a typical Windows Forms Net Assembly to VBS. But I get the following error:

![image](https://user-images.githubusercontent.com/62614400/121399499-c5553c00-c956-11eb-96f4-abfdfd3abf87.png)

The Application is the default Windows Forms Application from Visual Studio. Also note that I have compiled with Net Framework 5. I hope you can help me to solve this error.

![image](https://user-images.githubusercontent.com/62614400/121399651-eddd3600-c956-11eb-9f38-3cb00a05d5b4.png)

Best regards and thanks!

**Comment by med0x2e** [comment] 2021-07-16 16:24
Hi,

I've tried to reproduce the same error, but i can't seem to be able to do so, can you please share a PoC to reproduce the  issue from my side.

**Comment by rcaroncd** [comment] 2021-07-20 08:25
Hello,

To reproduce this error, you could simply use Visual Studio to generate a .NET application in Windows Forms (I used the default one). Then, you compile the application, and use that EXE for the G2JS. However, if you find it easier for me to provide you with the complete code of the project, I'll leave it attached without any problem.

Best regards and thanks!

[WindowsFormsApp2.zip](https://github.com/med0x2e/GadgetToJScript/files/6846630/WindowsFormsApp2.zip)

**Comment by med0x2e** [comment] 2021-07-21 13:05
Managed to create a working PoC, you must mark any WinForm class as internal, this will allow G2JS generated artifacts to trigger the `FormRunner` constructor's call prior to instantiating any other classes during deserialization from WSH scripts, check the steps below to reproduce the same from your side.

1. A basic WinForms application: TestForm.cs

```csharp 
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace WinFormsApp
{
   

    public class FormRunner
    {
        public FormRunner()
        {
            Application.EnableVisualStyles();
            Application.Run(new TestForm());
        }

        public static void Main()
        {
            new FormRunner();
        }

        internal class TestForm : Form
        {
            public Button button1;
            public TestForm()
            {
                button1 = new Button();
                button1.Size = new Size(40, 40);
                button1.Location = new Point(30, 30);
                button1.Text = "Click me";
                this.Controls.Add(button1);
                button1.Click += new EventHandler(button1_Click);


            }

            private void button1_Click(object sender, EventArgs e)
            {
                MessageBox.Show("Hello World");
            }

        }
    }

}
```

2. Compile from command line: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /platform:x86 testform.cs`
3. Generate VBS (using x86 built g2js executable): `GadgetToJScript.exe -b -w vbs -a testform.exe -o testform`


I hope this helps.

**Comment by med0x2e** [comment] 2021-07-28 07:26
Will close this issue, feel free to re-open in case not able to reproduce the steps above.

**Closed by med0x2e** 2021-07-28 07:26 UTC
